@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "ClinicBook Storage" #F4F6F6{
Class "<<interface>>\nClinicBookStorage" as ClinicBookStorage
Class JsonClinicBookStorage
Class JsonSerializableClinicBook
Class JsonAdaptedPerson
Class JsonAdaptedTag
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" ClinicBookStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> ClinicBookStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonClinicBookStorage .up.|> ClinicBookStorage
JsonClinicBookStorage ..> JsonSerializableClinicBook
JsonSerializableClinicBook --> "*" JsonAdaptedPerson
JsonAdaptedPerson --> "*" JsonAdaptedTag

@enduml
