@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedClinicBook" as VersionedClinicBook MODEL_COLOR
end box

[-> Model : undoClinicBook()
activate Model

Model -> VersionedClinicBook : undo()
activate VersionedClinicBook

VersionedClinicBook -> VersionedClinicBook :resetData(ReadOnlyClinicBook)
VersionedClinicBook --> Model :
deactivate VersionedClinicBook

[<-- Model
deactivate Model

@enduml
