@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

Participant ":LogicManager" as logic LOGIC_COLOR
Participant ":ClinicBookParser" as abp LOGIC_COLOR
Participant ":DeleteCommandParser" as dcp LOGIC_COLOR
Participant "command:DeleteCommand" as dc LOGIC_COLOR

[-> logic : execute
activate logic
logic -> abp ++: parseCommand(commandText)
create dcp
abp -> dcp
abp -> dcp ++: parse(arguments)
create dc
dcp -> dc ++: index
dc --> dcp --
dcp --> abp --: command
abp --> logic --: command

@enduml
